config/routes.rb
Viz::Application.routes.draw do
  get "pages/stockchart"
  resources :maps
  
  root :to => 'maps#index'

  get 'maps/stockchart', :to => redirect('/graphview.html')

  

end

app/models/map.rb
class Map < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
    @map = Map.new
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render action: 'show', status: :created, location: @map }
      else
        format.html { render action: 'new' }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params[:map]
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController



  def stockchart
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Viz</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/graphview.html.erb
<h2>Making a Graph </h2>


<div id="chartContainer"></div>
<script type="text/javascript" src="assets/javascripts/practiceGraph.js"></script>

app/views/maps/_form.html.erb
<%= form_for(@map) do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @map.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing map</h1>

<%= render 'form' %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<h2>eProf Dashboard Mock-Up</h2>

<!-- <h4><%= link_to "Example 2: Stock Chart", pages_stockchart_path %></h4> -->


<br />
<br />



<div id="dashboard"> 
  
  <div id="barchart">
    <button id="dataToggle">Data Toggle</button>
    <a href="#" id="dataReset">Reset Data</a>
  </div>
  
  <div id="barchart2">
    <button id="dataToggle2">Data Toggle</button>
    <a href="#" id="dataReset2">Reset Data</a>
  </div>

  <div id="barchart3">
    <button id="dataToggle3">Data Toggle</button>
    <a href="#" id="dataReset3">Reset Data</a>
  </div>

</div>



<script src="http://d3js.org/d3.v3.min.js"></script>
<script>

var dataset1 = [1, 3, 5, 6, 7, 14, 10, 20, 22, 25, 26, 35, 55, 76];
var dataset2 = [4, 3, 2, 6, 7, 1, 10, 12, 10, 5, 9, 22, 55, 76];

var dataset3 = [20, 22, 25, 26, 35, 55, 76];


var width = 350;
var height = 250;

var color = d3.scale.category20c();

var canvas = d3.select("#barchart")
  .append("svg")
  .attr("width", width)
  .attr("height", height)
  .attr("padding", 40);


function render(sub) {

// set up scale
var xScale = d3.scale.linear()
  .domain([0, d3.max(sub, function(d){ return d; })])
  .range([0, width]);        

// add horizontal bars
var bars = canvas.selectAll("rect")
    .data(sub) 
    .enter() 
    .append("rect")
    .attr("class", "bars")
    .transition()
    .delay(function (d,i) {
      return i * 200;
    })
    .duration( function(d,i){ return d * 100; })
    .attr("width", function(d) { return xScale(d); }) 
    .attr("height", 10)
    .attr("fill", function(d) { return color(d) })
    .attr("x", 50)
    .attr("y", function(d, i) { return i * 15 })
    .attr("stroke", function(d) { return color(d*25) })
    .on("mouseover", function(){
      d3.select(this).attr("stroke", "orange");
    })
    .on("mouseout", function(){
      d3.select(this).attr("stroke", "green");
    });

// set up axis
var xAxis = d3.svg.axis()
  .scale(xScale)
  .orient("bottom")
  .ticks(6);

// add x-axis
canvas.append("g")
  .attr("class", "axis")
  .attr("transform", "translate(50,220)")
  .style("opacity", 0.2)
  .call(xAxis);



d3.select("#dataToggle")
  .on("click", function() {
  
    dataset2 = [10, 12, 15, 20, 22, 24, 33, 40, 42, 43, 46, 50, 80, 31];
    
  canvas.selectAll('rect')
    .data(dataset2)
    .transition()
    .delay(function (d,i) {
          return i * 200;
    })
    .duration( function(d,i){ return d * 100; })
    .attr("width", function(d) { return xScale(d); }) 
    .attr("height", 10)
    .attr("fill", function(d) { return color(d) })
    .attr("x", 50)
    .attr("y", function(d, i) { return i * 15 })
    .attr("stroke", function(d) { return color(d*25) })
  });

};

  render(dataset1);

// 
// draw chart2
// 

var canvas = d3.select("#barchart2")
  .append("svg")
  .attr("width", width)
  .attr("height", height)
  .attr("padding", 40);


function render(sub) {

// set up scale
var xScale = d3.scale.linear()
  .domain([0, d3.max(sub, function(d){ return d; })])
  .range([0, width]);        

// add horizontal bars
var bars = canvas.selectAll("rect")
    .data(sub) 
    .enter() 
    .append("rect")
    .attr("class", "bars")
    .transition()
    .delay(function (d,i) {
      return i * 200;
    })
    .duration( function(d,i){ return d * 100; })
    .attr("height", function(d) { return xScale(d); }) 
    .attr("width", 10)
    .attr("fill", function(d) { return color(d) })
    .attr("y", 5000)
    .attr("x", function(d, i) { return i * 15 })
    .attr("stroke", function(d) { return color(d*25) });

// set up axis
var xAxis = d3.svg.axis()
  .scale(xScale)
  .orient("bottom")
  .ticks(6);

// add x-axis
canvas.append("g")
  .attr("class", "axis")
  .attr("transform", "translate(50,220)")
  .style("opacity", 0.2)
  .call(xAxis);



d3.select("#dataToggle2")
  .on("click", function() {
  
    dataset2 = [10, 12, 15, 20, 22, 24, 33, 40, 42, 43, 46, 50, 80, 31];
    
  canvas.selectAll('rect')
    .data(dataset2)
    .transition()
    .delay(function (d,i) {
          return i * 200;
    })
    .duration( function(d,i){ return d * 100; })
    .attr("width", function(d) { return xScale(d); }) 
    .attr("height", 10)
    .attr("fill", function(d) { return color(d) })
    .attr("x", 50)
    .attr("y", function(d, i) { return i * 15 })
    .attr("stroke", function(d) { return color(d*25) })
  });



};

  render(dataset3);
  
// 
// draw chart3
// 

var canvas = d3.select("#barchart3")
  .append("svg")
  .attr("width", width)
  .attr("height", height)
  .attr("padding", 40);


function render(sub) {

// set up scale
var xScale = d3.scale.linear()
  .domain([0, d3.max(sub, function(d){ return d; })])
  .range([0, width]);        

// add horizontal bars
var bars = canvas.selectAll("rect")
    .data(sub) 
    .enter() 
    .append("rect")
    .attr("class", "bars")
    .transition()
    .delay(function (d,i) {
      return i * 200;
    })
    .duration( function(d,i){ return d * 100; })
    .attr("width", function(d) { return xScale(d); }) 
    .attr("height", 10)
    .attr("fill", function(d) { return color(d) })
    .attr("x", 50)
    .attr("y", function(d, i) { return i * 15 })
    .attr("stroke", function(d) { return color(d*25) });

// set up axis
var xAxis = d3.svg.axis()
  .scale(xScale)
  .orient("bottom")
  .ticks(3);

// add x-axis
canvas.append("g")
  .attr("class", "axis")
  .attr("transform", "translate(50,220)")
  .style("opacity", 0.2)
  .call(xAxis);



d3.select("#dataToggle3")
  .on("click", function() {
  
    dataset2 = [10, 12, 15, 20, 22, 24, 33, 40, 42, 43, 46, 50, 80, 31];
    
  canvas.selectAll('rect')
    .data(dataset2)
    .transition()
    .delay(function (d,i) {
          return i * 200;
    })
    .duration( function(d,i){ return d * 100; })
    .attr("width", function(d) { return xScale(d); }) 
    .attr("height", 10)
    .attr("fill", function(d) { return color(d) })
    .attr("x", 50)
    .attr("y", function(d, i) { return i * 15 })
    .attr("stroke", function(d) { return color(d*25) })
  });

};


 // jQuery 
  
$(document).ready(function() {

  
$('#dataToggle').hover(function() {
  $(this).css({color: "blue" })
});

$('#dataReset').click( render(dataset1) );

$('#dataToggle2').hover(function() {
  $(this).css({color: "blue" })
});

$('#dataReset2').click( render(dataset3) );

}); 

// $('#dataToggle').hover(function() {$('this').css({background-color: "aliceblue" })});

</script>

<style>

body {
    margin-left: 20px;
}

#dashboard {
border: 2px black solid;
}

#barchart, #barchart2, #barchart3 {
  float: left;
  background-color: aliceblue;
  width: 32%;
  height: 350px;
  border: 1px blue solid;
  margin-right: 5px;

} 


svg {
  margin-top: 50px;
}
</style>

app/views/maps/new.html.erb
<h1>New map</h1>

<%= render 'form' %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<h1>Maps View </h1>
<p>Here will go League maps with their teams, and stats on hover, etc</p>



<div id="mapbox"></div>

<script type="text/javascript" src="http://d3js.org/d3.v3.min.js"></script>

<script type="text/javascript">
// set the size of our map
var width = 800;
    height = 800;

// set up the view of the map
var projection = d3.geo.mercator()
    .center([80,40]) // default [0,0], North America [100,30]
    .scale(500)    // default (150). zoom in w/ > values
    .rotate([-190,0]); // [longitude, latitude, roll], def [0,0,0]

// create svg window
var svg = d3.select("#mapbox").append("svg")
    .attr("width", width)
    .attr("height", height);
// geo path generator used to specify projection type
var path = d3.geo.path()
    .projection(projection);
// g is our appended svg
var g = svg.append("g");



// load and display the world, draws the map for us.
d3.json("app/assets/javascripts/world.json", function(error, topology) {
    g.selectAll("path")
        .data(topojson.feature(topology, topology.objects.countries)
            .features)
        .data(topojson.feature(topology, topology.objects.countries)
            .features) // data that defines countries
      .enter()
        .append("path") // act on all path elements
        .attr("d", path); // add data we're going to display

// add our bootcamps to their geo-location


</script>




<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>

app/views/pages/stockchart.html.erb
<h2>Stock Chart Template </h2>
<h5>Time series on x - Axis, Dollars on y - Axis</h5>

<div id="stockChart"></div>

<script src="http://d3js.org/d3.v3.min.js"></script>

<script>

// var dataset = []
// d3.csv("sp500.csv", function(data) {
//   dataset = data.map(function(d) {
//     return [ +d["date"], +d["price"] ];
//   };
//   console.log(dataset)
// });

var margin = {top: 10, right: 10, bottom: 100, left: 40},
    margin2 = {top: 430, right: 10, bottom: 20, left: 40},
    width = 960 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom,
    height2 = 500 - margin2.top - margin2.bottom;

var parseDate = d3.time.format("%b %Y").parse;

var x = d3.time.scale().range([0, width]),
    x2 = d3.time.scale().range([0, width]), 
    y = d3.scale.linear().range([height, 0]),
    y2 = d3.scale.linear().range([height2, 0]);

var xAxis = d3.svg.axis().scale(x).orient("bottom"),
    xAxis2 = d3.svg.axis().scale(x2).orient("bottom"),
    yAxis = d3.svg.axis().scale(y).orient("left");

var brush = d3.svg.brush()
  .x(x2)
  .on("brush", brushed);

var area = d3.svg.area()
  .interpolate("monotone")
  .x(function(d) { return x(d.date); })
  .y0(height)
  .y1(function(d) { return y(d.price); });

var area2 = d3.svg.area()
  .interpolate("monotone")
  .x(function(d) { return x2(d.date); })
  .y0(height2)
  .y1(function(d) { return y2(d.price); });

var svg = d3.select("#stockChart").append("svg")
  .attr("width", width + margin.left + margin.right)
  .attr("width", height = margin.top + margin.bottom);

svg.append("defs").append("clipPath") 
  .attr("id", "clip")
  .append("rect")
    .attr("width", width)
    .attr("height", height); 

var focus = svg.append("g")
  .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

var context = svg.append("g")
  .attr("transform", "translate(" + margin2.left + "," + margin2.top + ")");

d3.csv("http://localhost:3000/Viz/sp500.csv", function (data) {

  data.forEach(function(d) {
    d.date = parseDate(d.date);
    d.price = +d.price;
  });

  x.domain(d3.extent(data.map(function(d) { return d.date; })));
  y.domain([0, d3.max(data.map(function(d) { return d.price; }))]);
  x2.domain(x.domain());
  y2.domain(y.domain());

  focus.append("path")
    .datum(data)
    .attr("clip-path", "url(#clip)")
    .attr("d", area);

  focus.append("g")
    .attr("class", "x axis")
    .attr("transform", "translate(0," + height + ")")
    .call(xAxis);

  focus.append("g")
    .attr("class", "y axis")
    .call(yAxis);

  context.append("path")
    .datum(data)
    .attr("d", area2);

  context.append("g")
    .attr("class", "x axis")
    .attr("transform", "translate(0," + height2 + ")")
    .call(xAxis2);

  context.append("g")
    .attr("class", "x brush")
    .call(brush)
      .selectAll("rect")
      .attr("y", -6)
      .attr("height", height2 + 7);  

});

function brushed() {
  x.domain(brush.empty() ? x2.domain() : brush.extent());
  focus.select("path").attr("d", area);
  focus.select(".x.axis").call(xAxis);
}



</script>

<style type="text/css">
  
#stockChart {
  width: 80%;
  height: 700px;
}  

path {
  fill: steelblue;
}

.axis path,
.axis line {
  fill: none;
  stroke: #000;
  shape-rendering: crispEdges;
}

.brush .extent {
  stroke: #fff;
  fill-opacity: .125;
  shape-rendering: crispEdges;
}


</style>